### ISSUE TITLE
bad input not recognized

### ISSUE THREAD

**Issue by sir-pinecone** [sreedevik29/choose-your-story#1]
Hey Sree!

I just tried out your game. Good stuff! One thing I noticed is that if you don't input a correct action then the game continues on instead of asking you to try again. Perhaps you can make a function that is given the expected inputs and it will keep asking until you get it right? 

You may also want to experiment with adding a game loop. For example the main process loads the stories, then enters the user input loop. From here you can work on reducing the nested `if`s which make it hard to read and reason about the code. There are so many ways to design a game like this. Let me know if you want me to look it over and code review/provide guidance :)

**Comment by sreedevik29** [comment]
Hi Campo!

Thanks Campo! I just saw this message. Nafeu actually helped re-factor the game with me and made it as a decision tree on Saturday. So the whole while loop and if/else statements are gone. I'd love your input on the latest commit from him and see if there should be any improvements made there.

**Comment by sir-pinecone** [comment]
NP! I looked over the code and it's a lot cleaner. What you have is a good solution. Where you take it from here really depends on what you want to do with the game. For example, if you want to add more riddles with hints, then you can pull out the hint stuff and make it a more reusable concept. If you want to have more paths instead of A or B then it may make sense to make a graph or some custom data structure that solves the problem. It's hard to say without having a problem at hand. You never want to over design or even try to design the architecture ahead of time. You just simply don't know the answers until you go in and work on them. The caveat is when you're writing something that you've done soooo many times. You can skip some of the discovery steps, but you may miss out on an opportunity to experiment and find an even better way to do things.

My advice is to always approach the design as a discovery process. Your first implementation of the game looks exactly like that. You write the simplest code that solves your immediate problem, no matter how dumb it seems and then as things click into place you can "compress it" by pulling things out into functions/cleaning up with robust data structures, or even by rewriting entire chunks of it. Essentially, don't try to be fancy, just get the stuff to work. 

You'll grow fast and be really good if you simply do these three things: 

1. **Always consider the trade-offs** of every decision you make when programming. Every way of doing things has a cost and you need to understand those costs and be able to justify the decision. This will get easier over time as you research and understand how a computer works. 

2. **Learn about how computers work.** This can be done over time as you gain confidence in your programming skills and ability to reason about code. High-level languages like Python, Ruby, Java, etc make it easy for beginners to get their feet wet. Eventually you may want to try a more low-level language to get a true understanding of what code is doing. For example with C or C++, you're basically just working with memory directly and the primitives that a computer runs on. You create variables of different sizes (in terms of how many bits they hold) and you manage it all by understanding how computers use that memory. Some examples: an unsigned integer (unsigned = always positive) may be 32 bits large (can hold a number up to `2^32`); a signed 32-bit integer (can be negative or positive) holds `-2^31` to `2^32 - 1`; a double is an integer that is 64 bits; and so on. You work up from that and create code that is just moving data around in sequential ways. You build abstractions around these over time and your code is hella fast. High-level languages are abstractions that tend to hide the inner workings of the computer. They don't allow you to drop down to a low level when you need to and for that reason I consider them to be quite shitty for writing fast, high quality software.

Here's a neat example that may explain the benefit of learning about computer architecture. Consider needing to store the color of a pixel in your program. It uses the RGBA format (red, green, blue, alpha). One way to do it is to a class `Color` that has four member variables, `r`, `g`, `b`, `a`; you can have a constructor or setter function that makes sure the values are set within the `0-255` range; you can pass these Color instances around your program and use up a bunch of memory. Or, you can just simply store the entire RGBA value in a single 32-bit integer without any of that object orientated nonsense. The range is `0-255`, which fits exactly in `2^8` bits, right? It just so happens that `2^8` is also called a byte. So one byte is 8 bits, and a 32-bit integer is composed of `4 bytes (32 / 8)`. We just so happen to need four 8 bit values for the RGBA, so you can literally pack it all into one integer using bit shifting, e.g. `int color = (u8)(A<< 24) | (u8)(R<< 16) | (u8)(G << 8) | (u8)(B << 0);`. Say someone tries to set the red value to `3249` for kicks - that's fine because you're casting the number to an unsigned byte (the `(u8)` part) and that causes a number larger than `2^8` to wrap back to 0. I realize this is a lot of new info and I don't expect you to follow without doing some followup reading, but hopefully you can see how learning about the inner workings of computers can give you a super power when it comes to writing good code. You can even do that RGBA trick in a high-level language that supports bit shifting. The real value is in having another tool at your disposal.

2. **Never fear rewriting your code.** Sometimes you have to code things 5+ times in many different ways until you really understand the problem and can devise a solid solution. The more times you rewrite something, the better it'll be. If you think of 10 ways to structure your adventure game logic and actually code them, then you'll now have 10 new ways of thinking about related problems. A lot of people get into this weird place where they work hard to solve a hard problem and then they're so afraid of touching it once it works. "Just leave it as is! It was so hard to get it to work in the first place, if I make any change then it could break and I'll have to struggle again!". Don't do that :)

You're in a good position right now since you're so new to this and haven't been corrupted by bad programmers and bad ideas from the countless bad books and stackoverflow-type sites out there. Newbies tend to write code that gets right to the point because their mind isn't filled with dumb "patterns" or the dogma of programming ideologies. 

Anyways, I didn't expect this to turn into an advice giving session haha. Hope you don't mind. If this stuff interests you, I have a lot more to say and can share some notes I've written on improving as a programmer. I went down that bad path and have returned to the light, so it would be my pleasure to help keep you on the right path :)

**Comment by sreedevik29** [comment]
Hi Campo,

So sorry I'm getting back to this late. I just started my courses again so I've just been reorienting a bit.

Regarding your advice - I really appreciate in sharing all this! I've saved this message just to be able to re-read. I think what you said about learning how computers works is especially important because I realized that writing code and knowing this will implement something on a surface level will only get you so far. Like you said, getting a true understanding of what the code is actually doing in the computer is much more beneficial. Obviously a lot of the information is very new to me and I am continuously learning how to get away from just abstract level thinking that I've historically been used to. But I'm definitely learning. 

I think I definitely need to get into the habit of re-writing code and having different approaches to solve a problem (especially after gaining more knowledge). When Nafeu helped re-factor this particular game, I was open to different avenues of problem-solving and it was really neat. It's amazing to see how people write different code to solve the same problem - shows how dynamic coding obviously is. 

Anyways, I appreciate your thoughts! Honestly, keep them coming any time. :)

**Comment by sir-pinecone** [comment]
No need to apologize :) I'm glad you got something out of my ramblings. 

> It's amazing to see how people write different code to solve the same problem

Yes! It's so cool. You will rarely see any two people write the same code for any given problem. Having said that, the differences tend to exist at the syntactic level. It's very possible to have the same computational solutions and this can be explored by viewing the machine instructions that a compiler outputs. 

I'm not sure if I've mentioned this before but the textbook [Computer Systems: A Programmer's Perspective](https://www.amazon.com/Computer-Systems-Programmers-Perspective-3rd/dp/013409266X/) is an excellent way to learn about how things work under the hood. I'm working my way through it right now and have learned so much, even for basic things that I never bothered to learn in the past. Unfortunately it's an expensive book. I paid around $200 for it! Definitely a worthwhile investment though. The authors also teach a course that is based on the book content. The [videos are online](https://www.cs.cmu.edu/~213/schedule.html) too! I started a gitbook to summarize what I've read and you can see that [here](https://sir-pinecone.gitbooks.io/notes-for-comp-systems-a-programmers-perspective/content/) - I'm behind of course, which is part of the reason I'm sharing this. Perhaps by making it known I will incentivize myself to work on it haha.

Looking forward to future chats about programming and to see how you progress. Feel free to hit me up anytime if you want advice or to just chat about tech.
